### ISSUE TITLE
Couldn t find episode/season queried

### ISSUE THREAD

**Issue by Doctor2023** [rhenwinch/Flixclusive#29] opened 2023-12-10 11:34 UTC
![Screenshot_20231210-122356_Screenshot Easy](https://github.com/rhenwinch/Flixclusive/assets/129991276/91b1e899-9833-40b6-b056-4a2a5d863183)

I get this problem in some series and movies this problem and error and I get this message

**Comment by rhenwinch** [comment] 2023-12-10 12:53
What show is this? what season and episode are u trying to watch?

**Comment by Doctor2023** [comment] 2023-12-10 12:58
> What show is this? what season and episode are u try

Series Rugrats

**Comment by rhenwinch** [comment] 2023-12-10 14:35
meta/providers issue. Both flixhq and lookmovie supports only S1 Episode 1-5 and S2

**Comment by Doctor2023** [comment] 2023-12-10 14:44
> meta/providers issue. Both flixhq and lookmovie supports only S1 Episode 1-5 and S2 upto 13 episodes. Idk why TMDB says its over 13 eps. Maybe it hasnt been released yet...

It would be better if they added more providers in Flixclusive

**Comment by rhenwinch** [comment] 2023-12-10 14:45
Yep confirmed, it was absolutely TMDB meta error. Episode 13 should be the last episode since its a combination of the last two episodes.

https://www.themoviedb.org/tv/124920-rugrats/season/2/episode/13
![image](https://github.com/rhenwinch/Flixclusive/assets/52451354/02ec065f-31ca-4ac9-bc99-992ce8ee9ffc)

Cant do nothing with this one since its from the meta-end so I might close this one for awhile.

**Closed by rhenwinch** 2023-12-10 14:45 UTC

**Comment by rhenwinch** [comment] 2023-12-10 14:47
If u needa comment on adding new providers pls refer here #13
