### ISSUE TITLE
Subtitles 

### ISSUE THREAD

**Issue by WiseMikeyK** [rhenwinch/Flixclusive#35] opened 2023-12-15 00:09 UTC
I noticed the subtitles switch is stuck on is there anywhere to fix this? Thank you in advance.

**Comment by oathzed** [comment] 2023-12-15 06:30
Duplicate of #23

**Comment by rhenwinch** [comment] 2023-12-15 09:10
Duplicate of #23 

this has been fixed now for the next coming patch.

**Comment by rhenwinch** [comment] 2023-12-15 09:11
this has been fixed now for the next coming patch. expect it soon !

**Closed** 2024-02-16 16:48 UTC
