### ISSUE TITLE
Cannot find source 

### ISSUE THREAD

**Issue by injusticedevil** [rhenwinch/Flixclusive#62] opened 2024-03-21 10:22 UTC
### Steps to reproduce

I downloaded the app first and tried to watch Oppenheimer but it shows cannot find source same for the other movies and TV shows 

### Expected behavior

I really expected it to work like every other movie app 

### Actual behavior

When I try to wat h any movie or a tv show it always shows cannot find source I even changed to every dns available and tried out it but always show cannot find source 

### Crash logs (or stack trace)

![Screenshot_2024-03-21-15-49-50-670_com flixclusive](https://github.com/rhenwinch/Flixclusive/assets/148668084/4dce554a-ca2d-4056-b63d-20c20060429d)

### Flixclusive version

1.4.0-beta1

### Android version

Android 11

### Device

Poco m2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the **[latest version](https://github.com/rhenwinch/Flixclusive/releases/latest)**.

**Comment by Hammoudi99** [comment] 2024-03-21 13:28
Same

**Comment by abhinavdatta** [comment] 2024-04-11 02:49
Same it says "CANNOT FETCH STREAM API ERROR(403-)".
I use android 11 
Model :- Samsung galaxy s20

**Comment by rhenwinch** [comment] 2024-05-24 04:45
> Providers system is on [prerelease tag](https://github.com/rhenwinch/Flixclusive/releases/tag/pre-release). This somehow should be temporarily fixed.

Sorry for the late reply! somehow a duplicate of #13

**Closed by rhenwinch** 2024-05-24 04:45 UTC
