### ISSUE TITLE
Shows in progress got unplayable

### ISSUE THREAD

**Issue by ItzNuggetz** [rhenwinch/Flixclusive#64] opened 2024-04-06 20:19 UTC
### Steps to reproduce

1. The shows which I had in progress used to play from where I left off but now nothing seems to play or work and says I'm sorry this is not yet watchable.
2. There were other list of shows with no EP titles or thumbnails 
3. I tried playing other shows but none of them were watchable and had the same message. 

### Expected behavior

This should not happen since these shows were playable at first. 

### Actual behavior

![Screenshot_20240407_014410](https://github.com/rhenwinch/Flixclusive/assets/166253246/6ff570ac-6921-4047-9f77-bca07124b07f)
I'm sorry, this is not yet watchable!

### Flixclusive version

1.4.0-beta1

### Android version

Android 13

### Device

Honor 90

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the **[latest version](https://github.com/rhenwinch/Flixclusive/releases/latest)**.

**Comment by ItzNuggetz** [comment] 2024-04-06 21:40
For flix HQ most content are either failed to extract or the content is not watchable which is same for look movie and for super stream we have API error message 403-
![Screenshot_20240407_025726](https://github.com/rhenwinch/Flixclusive/assets/166253246/a6fcc541-5fec-4e01-9621-746ee1fc7932)

**Comment by rhenwinch** [comment] 2024-05-24 04:41
> Providers system is on [prerelease tag](https://github.com/rhenwinch/Flixclusive/releases/tag/pre-release). This somehow should be temporarily fixed.

Old providers went bonkers.
 
Sorry for the late reply! duplicate of #13

**Closed by rhenwinch** 2024-05-24 04:41 UTC

**Comment by ItzNuggetz** [comment] 2024-05-29 09:27
Is there any expectation of getting it better providers and the app running soon?

**Comment by rhenwinch** [comment] 2024-05-29 12:18
hopefully. im currently creating a new set of providers from sudo-flix's (forked mw)

**Comment by ItzNuggetz** [comment] 2024-06-05 11:33
Hi I'm on the pre release but some of the shows like Panchayat which is from Amazon prime says this is not playable and just like this one I would request to have the categories section based on Indian OTT platforms in top TV networks or movie companies like Hoichoi which has bengali content, Zee5, Hotstar Originals and many more they got exclusive content which could be added as a category. There are other shows which might show up on Flix but due to absence of meta data or the content being removed from the site doesn't play at all, if that can be fixed it would be great. Until then thank you for creating this app. Kudos!

**Comment by rhenwinch** [comment] 2024-06-06 08:30
@ItzNuggetz would you mind opening up a new issue for this? Thanks
