### ISSUE TITLE
Bug on the new version 

### ISSUE THREAD

**Issue by EinsteinOfTech** [rhenwinch/Flixclusive#31] opened 2023-12-10 12:24 UTC
![Screenshot_20231210-131215_Flixclusive](https://github.com/rhenwinch/Flixclusive/assets/106039148/5d6cacb8-2a4f-4973-9a48-a3e2195a5897)

**Comment by rhenwinch** [comment] 2023-12-10 12:52
Godzilla Minus One is, unfortunately, not yet available on any of the providers the app currently has. I'm closing this for now.

**Comment by rhenwinch** [comment] 2023-12-10 12:52
but does this happen on other movie/shows?

**Comment by rhenwinch** [comment] 2023-12-22 11:50
closing this as this could be considered as a duplicate of #13

**Closed by rhenwinch** 2023-12-22 11:50 UTC
