### ISSUE TITLE
This is not yet watchable issue

### ISSUE THREAD

**Issue by LoveSosaaa** [rhenwinch/Flixclusive#67] opened 2024-04-12 03:40 UTC
### Steps to reproduce

Click on any show or movie

### Expected behavior

For the show/movie to start working

### Actual behavior

pops up saying "cant connect to superstream api or "this is not watchable yet"

### Flixclusive version

Latesr

### Android version

11

### Device

moto g play 2023

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the **[latest version](https://github.com/rhenwinch/Flixclusive/releases/latest)**.

**Comment by johnmdelport** [comment] 2024-04-16 09:27
same issues . cant play anything, main screen dissapears, cant access settings. When will a full working version be made available? Best layout I ever seen. Cant wait to see the fully operational version.  Well done. Deserves Golden Accolades for programming & presentation. Keep up the excellence. Best Regards John 69yrs (end user)

**Comment by popcorn2024ok** [comment] 2024-04-17 19:38
![2024_04_17_21 34 59](https://github.com/rhenwinch/Flixclusive/assets/165403113/fd0075b1-9d3f-4bea-884f-56c922b84743)

I can t play any movie and series I get this error message when I play the video any movie and series

**Comment by popcorn2024ok** [comment] 2024-04-17 19:49
![20240417_214813](https://github.com/rhenwinch/Flixclusive/assets/165403113/b89cb4a9-90dd-4758-9f0c-d04e08d1e634)

I m sorry this is not yet watchable

**Comment by rhenwinch** [comment] 2024-05-24 04:40
> Providers system is on [prerelease tag](https://github.com/rhenwinch/Flixclusive/releases/tag/pre-release). This somehow should be temporarily fixed.

Sorry for the late reply! duplicate of #13

**Closed by rhenwinch** 2024-05-24 04:40 UTC
