### ISSUE TITLE
Flixclusive application does not work videos

### ISSUE THREAD

**Issue by Doctor2023** [rhenwinch/Flixclusive#14] opened 2023-10-15 13:43 UTC
![Screenshot_20231015-154045_Flixclusive](https://github.com/rhenwinch/Flixclusive/assets/129991276/5dd2d1eb-53c9-4381-8c8f-c35d1e38bc1e)

Hello friend The movies and series don t come out This message sells me click on some movies and series.

Error while fetching  data

please apk v1.3.0

**Comment by rhenwinch** [comment] 2023-11-08 13:25
helo, does this happen everytime?

**Comment by Doctor2023** [comment] 2023-11-09 21:25
> helo, does this happen everytime?

Hello friend If it happens all the time but the apk application stopped working, there are no changes and improvements for the year 2023 we are in November 2023 please apk v.1.3.0 version android tv

**Comment by rhenwinch** [comment] 2023-11-10 03:54
> some movies and series

what specific movies/tv shows are these?

**Comment by Doctor2023** [comment] 2023-11-10 07:55
> > some movies and series
> 
> what specific movies/tv shows are these?

I get that the application apk is under maintenance and v1.3.0 is still not available

**Comment by rhenwinch** [comment] 2023-12-07 00:00
#18

**Comment by rhenwinch** [comment] 2023-12-07 00:18
Duplicate of #18

**Comment by rhenwinch** [comment] 2023-12-07 00:18
reopen this if its not a duplicate of that said issue

**Closed by rhenwinch** 2023-12-07 00:18 UTC
Labels: bug
