### ISSUE TITLE
Movies, series is not playing.Providers is not working. 4k not streaming

### ISSUE THREAD

**Issue by tanhatahiya** [rhenwinch/Flixclusive#66] opened 2024-04-08 16:03 UTC
### Steps to reproduce

Movies, series is not playing.Providers is not working. 4k not streaming

### Expected behavior

Movies, series should be playing.Providers should be working. 4k should be streaming

### Actual behavior

Movies, series is not playing.Providers is not working. 4k not streaming

### Flixclusive version

1.4.0-beta1

### Android version

Android 11

### Device

Infinix

### Other details

Movies, series is not playing.Providers is not working. 4k not streaming

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the **[latest version](https://github.com/rhenwinch/Flixclusive/releases/latest)**.

**Comment by rhenwinch** [comment] 2024-05-24 04:39
Providers system is on [prerelease tag](https://github.com/rhenwinch/Flixclusive/releases/tag/pre-release). This somehow should be temporarily fixed.

**Comment by rhenwinch** [comment] 2024-05-24 04:39
Also, duplicate of #13

**Closed by rhenwinch** 2024-05-24 04:39 UTC
