### ISSUE TITLE
how to add providers 

### ISSUE THREAD

**Issue by LoveSosaaa** [rhenwinch/Flixclusive#65] opened 2024-04-08 13:45 UTC
### Steps to reproduce

It says sources not found.

### Expected behavior

When trying to watch any movie or show it says sources not found

### Actual behavior

?

### Crash logs (or stack trace)

its not crashing or doing anything weird

### Flixclusive version

Newest

### Android version

android 11

### Device

moto g play 2023

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the **[latest version](https://github.com/rhenwinch/Flixclusive/releases/latest)**.

**Comment by Aaron261099** [comment] 2024-04-09 05:26
Same issue.In the latest prerelease build how to add providers?

**Comment by LoveSosaaa** [comment] 2024-04-12 03:32
> Same issue.In the latest prerelease build how to add providers?

yea not sure what they did to it

**Comment by rhenwinch** [comment] 2024-05-24 04:44
> Providers system is on [prerelease tag](https://github.com/rhenwinch/Flixclusive/releases/tag/pre-release). This somehow should be temporarily fixed.

> Same issue.In the latest prerelease build how to add providers?

I've pre-included the built-in providers of the app. Adding providers shouldn't be a hassle no more.

Sorry for the late reply! duplicate of #13

**Closed by rhenwinch** 2024-05-24 04:44 UTC
