### ISSUE TITLE
Android TV

### ISSUE THREAD

**Issue by anon45-ui** [rhenwinch/Flixclusive#110] opened 2024-07-21 08:32 UTC
### Describe your suggested feature

Need to work on the Android TV verison

**Comment by Benlee1129** [comment] 2024-07-22 14:23
The Flixclusive app works on android TV but not integrated well.
I suggest with a change of the design in landscape and the main menu is placed on the lefthand side for fitting android tv.

**Comment by rhenwinch** [comment] 2024-07-22 14:40
Also closing this as its already been mentioned on an existing issue.

Duplicate of #19

**Closed by rhenwinch** 2024-07-22 14:40 UTC
Labels: enhancement
